version: '2'
services:
  app:
    build: app
    image: "freija/whereispatrick"
    volumes:
     - "./data:/data"
     - "./config:/config"
    environment:
     - "STATIC_URL_BASE=http://localhost:8000"
  static:
    image: "nginx:alpine"
    volumes:
      - "./data:/usr/share/nginx/html:ro"
  images:
    build: images
    image: "freija/images"
    volumes:
      - "./data:/data"
